version: "3"
services:
  notebook:
    build: .
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    user: root
    environment:
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
      NB_UID: "${UID}"
