version: "3"
services:
  notebook:
    image: dmeliza/comp-neurosci:latest
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./.:/home/jovyan/work
    user: root
    environment:
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
      NB_UID: "${UID}"
